name       : xprop
version    : 1.2.5
release    : 7
source     :
    - https://www.x.org/releases/individual/app/xprop-1.2.5.tar.gz : b7bf6b6be6cf23e7966a153fc84d5901c14f01ee952fbd9d930aa48e2385d670
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xprop
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-macros)
description: |
    X.Org Applications - xprop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
