name        : xprop
version     : 1.2.2
release     : 3
source      :
    - http://xorg.freedesktop.org/releases/individual/app/xprop-1.2.2.tar.gz : 3db78771ce8fb8954fb242ed9d4030372523649c5e9c1a9420340020dd0afbc2
license     : GPL-3.0+
component   : xorg.apps
summary     : X.Org Applications - xprop
builddeps   :
    - pkgconfig(x11)
description : |
    X.Org Applications - xprop
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
