name       : xprop
version    : 1.2.3
release    : 5
source     :
    - https://www.x.org/releases/individual/app/xprop-1.2.3.tar.gz : 82c13f40577e10b6f3f0160a21b1e46c00a0c719aa560618b961c453e1b5c80d
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xprop
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-macros)
description: |
    X.Org Applications - xprop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
