name       : xprop
version    : 1.2.4
release    : 6
source     :
    - https://www.x.org/releases/individual/app/xprop-1.2.4.tar.gz : dddb6e208ffa515e68f001c22077a465f1365a4bcf91d9b37f336a6c0d15400d
license    : MIT
component  : xorg.apps
summary    : X.Org Applications - xprop
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xorg-macros)
description: |
    X.Org Applications - xprop
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
